/** PRODUCTS */
export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const SINGLE_PRODUCT_INIT = "SINGLE_PRODUCT_INIT";
export const SINGLE_PRODUCT_STORE = "SINGLE_PRODUCT_STORE";

export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const FETCH_ALL_PRODUCTS_START = "FETCH_ALL_PRODUCTS_START";
export const FETCH_ALL_PRODUCTS_SUCCESS = "FETCH_ALL_PRODUCTS_SUCCESS";
export const FETCH_ALL_PRODUCTS_FAIL = "FETCH_ALL_PRODUCTS_FAIL";

export const FETCH_MAIN_PRODUCTS_START = "FETCH_MAIN_PRODUCTS_START";
export const FETCH_MAIN_PRODUCTS_SUCCESS = "FETCH_MAIN_PRODUCTS_SUCCESS";
export const FETCH_MAIN_PRODUCTS_FAIL = "FETCH_MAIN_PRODUCTS_FAIL";

export const FETCH_SUB_PRODUCTS_START = "FETCH_SUB_PRODUCTS_START";
export const FETCH_SUB_PRODUCTS_SUCCESS = "FETCH_SUB_PRODUCTS_SUCCESS";
export const FETCH_SUB_PRODUCTS_FAIL = "FETCH_SUB_PRODUCTS_FAIL";

/** LOGIN */
export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

/** BUYER */
export const FETCH_ALL_BUYERS_START = "FETCH_ALL_BUYERS_START";
export const FETCH_ALL_BUYERS_SUCCESS = "FETCH_ALL_BUYERS_SUCCESS";
export const FETCH_ALL_BUYERS_FAIL = "FETCH_ALL_BUYERS_FAIL";

/*  orders */
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
