export const FETCH_PRODUCT_SUBCAT_START = "FETCH_PRODUCT_SUBCAT_START";
export const FETCH_PRODUCT_SUBCAT_SUCCESS = "FETCH_PRODUCT_SUBCAT_SUCCESS";
export const FETCH_PRODUCT_SUBCAT_FAIL = "FETCH_PRODUCT_SUBCAT_FAIL";
