export const FETCH_PRODUCT_SUBCAT_START = "FETCH_PRODUCT_SUBCAT_START";
export const FETCH_PRODUCT_SUBCAT_SUCCESS = "FETCH_PRODUCT_SUBCAT_SUCCESS";
export const FETCH_PRODUCT_SUBCAT_FAIL = "FETCH_PRODUCT_SUBCAT_FAIL";

export const FETCH_DAILYPRODUCTS_START = "FETCH_DAILYPRODUCTS_START";
export const FETCH_DAILYPRODUCTS_SUCCESS = "FETCH_DAILYPRODUCTS_SUCCESS";
export const FETCH_DAILYPRODUCTS_FAIL = "FETCH_DAILYPRODUCTS_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const CANCEL_THE_CART = "CANCEL_THE_CART";
export const INCREASE_PRODUCT_QTY = "INCREASE_PRODUCT_QTY";
export const DECREASE_PRODUCT_QTY = "DECREASE_PRODUCT_QTY";
